version: "3"

tasks:
  up:local:backend:
    desc: Build and run local docker-compose stack
    cmds:
      - docker compose -f docker-compose.yml --env-file ./secrets/names.env build
      - docker compose -f docker-compose.yml --env-file ./secrets/names.env up

  build:prod:backend:tag:
    desc: Build backend image, push to registry "<tag>"
    dotenv:
      - ./secrets/names.env
    cmds:
      - >
        docker build -f ./backend/Dockerfile
        -t registry.thomasjbarlow.com/names-backend:{{.CLI_ARGS}} .
      - docker push registry.thomasjbarlow.com/names-backend:{{.CLI_ARGS}}

  build:prod:backend:
    desc: Build backend image, push to registry "latest"
    dotenv:
      - ./secrets/names.env
    cmds:
      - >
        docker build -f ./backend/Dockerfile
        -t registry.thomasjbarlow.com/names-backend:latest .
      - docker push registry.thomasjbarlow.com/names-backend:latest

  deploy:prod:tag:
    desc: Deploy the stack to the swarm
    dotenv:
      - ./secrets/names.env
    vars:
      NAMES_VERSION: '{{default "latest" .CLI_ARGS}}'
    cmds:
      - |
        export NAMES_VERSION={{.NAMES_VERSION}}
        docker stack deploy --with-registry-auth -c stack.yml names
      - |
        stack_name="names"
        expected_replicas=$(
          docker stack services "$stack_name" --format json \
            | jq -s -r 'map(.Replicas | split("/") | .[1] | tonumber) | add'
        )
        start_time=$SECONDS
        timeout=60
        while true; do
          ready_replicas=$(
            docker stack services "$stack_name" --format json \
              | jq -s -r 'map(.Replicas | split("/") | .[0] | tonumber) | add'
          )
          elapsed=$((SECONDS - start_time))
          echo "Ready replicas: $ready_replicas / $expected_replicas"
          if [ "$ready_replicas" -eq "$expected_replicas" ]; then
            echo "All services are healthy!"
            break
          fi
          if [ "$elapsed" -gt "$timeout" ]; then
            echo "Timeout waiting for services to become healthy!"
            exit 1
          fi
          sleep 1
        done
